all:	HashMapTester HashMapDriver1 HashMapDriver2
 
#EntryTester:	Entry.h Entry.cpp EntryTester.cpp
#	g++ -g -o EntryTester EntryTester.cpp Entry.cpp

#LinkedHashEntryTester:	LinkedHashEntryTester.cpp LinkedHashEntry.h LinkedHashEntry.cpp Entry.h Entry.cpp
#	g++ -g -o LinkedHashEntryTester LinkedHashEntryTester.cpp LinkedHashEntry.cpp Entry.cpp

HashMapTester:	HashMapTester.cpp HashMap.h HashMap.cpp LinkedHashEntry.h LinkedHashEntry.cpp Entry.h Entry.cpp
	g++ -g -o HashMapTester HashMapTester.cpp HashMap.cpp LinkedHashEntry.cpp Entry.cpp

HashMapDriver1:	HashMapDriver1.cpp HashMap.h HashMap.cpp LinkedHashEntry.h LinkedHashEntry.cpp Entry.h Entry.cpp
	g++ -g -o HashMapDriver1 HashMapDriver1.cpp HashMap.cpp LinkedHashEntry.cpp Entry.cpp

HashMapDriver2:	HashMapDriver2.cpp HashMap.h HashMap.cpp LinkedHashEntry.h LinkedHashEntry.cpp Entry.h Entry.cpp
	g++ -g -o HashMapDriver2 HashMapDriver2.cpp HashMap.cpp LinkedHashEntry.cpp Entry.cpp


